### ISSUE TITLE
Support for Hermes & React Native

### ISSUE THREAD

**Issue by itsezc** [surrealdb/surrealdb.js#103]
While using this library on RN / Expo workflows, Hermes is used as the JS engine and this does not support `URL.protocol` it'd be great if there's a workaround for this, allowing the JS library to also support React Native projects.

**Comment by itsezc** [comment]
Created an upstream issue on Hermes for tracking: https://github.com/facebook/hermes/issues/987

**Comment by itsezc** [comment]
For best compatibility, it would be great if we could avoid `URL` altogether to avoid issues with Hermes and similar engines, or at least override in the config options.

**Comment by kearfy** [comment]
@tmikov you are entirely correct on that. It has however been supported in most runtimes like browsers, node and deno (which this library is intended for). Because it's completely supported in all those environment I opted to use it, without realising it would not be part of the ECMA specification. All though this library is not officially targeting Hermes, I'm happy to make changes like this to make the library work for as much targets as possible!
