### ISSUE TITLE
Vite falling back to node ws (doesn't exist) on client side

### ISSUE THREAD

**Issue by tristan-f-r** [surrealdb/surrealdb.js#11]
# Reproducing

- Create a vite project
- Use surrealdb.js
- See the Buffer not defined error
- Add vite polyfill for buffer
- See the class is not defined

**Comment by Choooks22** [comment]
The issue isn't caused by surrealdb.js having circular dependencies (it doesn't have any), but by vite not using the bundled file created by webpack pointed to by the `browser` field, since it supports the modern `exports` field.

Vite then tries to resolve the now invalid websocket workaround and resolves to using node's `ws` package, which obviously would not work outside node.

**Comment by Choooks22** [comment]
Tested "workaround", does not work for vite's dev server:
- Patch `surrealdb.js` using `yarn patch` or similar.
- Edit `package.json` and point `exports.import` from `./index.js` to `./dist/web/index.js`.
- Run `vite build` then `vite preview`.

**Comment by ilearnio** [comment]
@Choooks22 Applying your patch helped to fix the "Buffer is not defined" error but then it doesn't work when importing it in a ESM projects (Using official Vite + Svelte `npm init vite@latest` setup). I still can't import Surreal class.

```js
import Surreal from 'surrealdb.js' // <-- Surreal is undefined
import * as Surreal from 'surrealdb.js' // <--Surreal is an empty object, well it has just a signle property `__esModule: true`
```
