### ISSUE TITLE
feat: change function should return allways an array

### ISSUE THREAD

**Issue by mathe42** [surrealdb/surrealdb.js#15]
The change function in https://github.com/surrealdb/surrealdb.js/blob/main/src/index.ts#L395 returns a single object or an array of objects.

I personaly think it would be nice to allways return an array, This can be done with a simple change this is therefore a discussion if that would be a good idea.

**Comment by btmnk** [comment]
I had an idea of inferring the return type from the passed id, since it would only return an array if the first param is a table name, right?
If we can infer it by checking if the first param matches "*:*" we could predict that the return type is a single object and an array otherwise. 
(We can safely do this since we already decide for the array with `typeof id === "string" && id.includes(":")`)

It could look something like this:
```ts
	change<Thing extends string, T extends object, U extends object = T>(
		thing: Thing,
		data?: Partial<T> & U
	): Thing extends `${infer Table}:${infer ID}`
		? Promise<T & U & { id: string }>
		: Promise<Array<T & U & { id: string }>> {
		const id = guid();
		return this.wait().then(() => {
			return new Promise((resolve, reject) => {
				this.once(id, (res) =>				
					this.#output(res, "change", thing, resolve, reject)
				);
				this.#send(id, "change", [thing, data]);
			});
		});
	}
```

I wasn't able to get the types to become properly compatible but I think the idea gets through.
With that the consumer could work comfortably with the change method with the correct return type for the use case.

**Comment by mathe42** [comment]
@btmnk Looks good! woll give it a try. I currently don't know what happens if the Table only has 1 row...

**Comment by kearfy** [comment]
Did an implementation of the above concept in #80
