### ISSUE TITLE
Bug: need better error messaging

### ISSUE THREAD

**Issue by ralyodio** [surrealdb/surrealdb.js#194]
### Describe the bug

I can't login after upgrading and all it says is "there was a problem with authentication" which is useless to me.

### Steps to reproduce

upgrade, then try to signin via app.

### Expected behaviour

should let me signin.

### SurrealDB version

1.0.0+20230913.54aedcd for linux on x86_64

### SurrealDB.js version

0.11.0

### Contact Details

anthony@chovy.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ralyodio** [comment]
I repoted this in discord like 3 months ago and they said it was fixed on nightly, but that hasn't happened I guess.

**Comment by kearfy** [comment]
Closing this as we:
- Solved this in Discord
- It's not an issue in the SDK (these errors are returned from SurrealDB)

For reference, @ralyodio was using the deprecated `NS`, `DB` and `SC` properties, which should be `namespace`, `database` and `scope` respectively since the last release of the SDK :)
