### ISSUE TITLE
Bug: SELECT FROM ONLY returns a list instead of object

### ISSUE THREAD

**Issue by wedobetter** [surrealdb/surrealdb.js#326]
### Describe the bug

Query: `await db.query("SELECT * OMIT password FROM ONLY user:xyz")` should return an object instead of a list and be consistent with the backend 

### Steps to reproduce

await db.query("SELECT * OMIT password FROM ONLY user:xyz")

### Expected behaviour

An object being return instead of a list

### SurrealDB version

1.5.3

### JavaScript SDK version

1.0.0-beta.19

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Hey @wedobetter, I believe that you are referring to the outer array here returned by the query method, which holds to results of all queries sent to SurrealDB. For example, if you were to remove the ONLY keyword, you should find another nested array. Since you sent one query in, you can safely take index 0 fron the returned array, which should be the result of the first query you sent
