### ISSUE TITLE
Bug: utility function jsonify() does not handle datetime after 2.0.0 change

### ISSUE THREAD

**Issue by omencat** [surrealdb/surrealdb.js#359]
### Describe the bug

I originally opened an [issue](https://github.com/surrealdb/surrealdb/issues/4949) on the [surreal/surrealdb](https://github.com/surrealdb/surrealdb) repo.

after 2.0.0 SurrealDB no longer eagerly converts a string into a datetime. An implicit d prefix or cast using <datetime> is required instead.

### Steps to reproduce

```
      await db.insert("solar_metrics", {
        ...message,
        timestamp: '${message.timestamp.toISOString()}',
        localTimestamp: '${message.localTimestamp.toISOString()}',
      })

...

const fmtMsg = jsonify(message)
      await db.insert("solar_metrics", fmtMsg)
...

```

### Expected behaviour

the jsonify utility should handle the cast to datetime or prefix with `d`

If I send a raw insert with the `d` in surrealist, it works. Im just not sure how to do this with the SDK.

### SurrealDB version

2.0.4 for macos on aarch64

### JavaScript SDK version

1.0.6

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kearfy** [comment]
Hey @omencat, this is expected behaviour. In the 1.0.0 version of the SDK and onwards you need to send over actual `Date` values to SurrealDB, and likewise will you receive values in that format going forwards. As for the `jsonify` utility, it is there to convert values in their native format to how SurrealDB would represent them in the previously used json protocol.

Hope this helps!
