### ISSUE TITLE
Compatibility check on connect

### ISSUE THREAD

**Issue by netcodedev** [surrealdb/surrealdb.js#84]
Switching from beta 8 to beta 9 caused a lot of trouble which made me think that it might be nice if the library had some type of compatibility check when connecting to the server.

**Comment by kearfy** [comment]
Hi @netcodedev, while I like your suggestion, keep in mind that surrealdb is still in beta! There was a slight hickup because of a change in the websocket protocol. I patched it first thing this week after easter and we put out the v0.6.0 release of the library Tuesday evening.

Once a stable 1.0.0 release is out the protocol will stay backwards compatible until a new major release. Hope that helps!

**Comment by netcodedev** [comment]
Hi @kearfy 
Thank you for your quick reply. While I still mostly agree and of course know that surrealdb is still in beta I hope you may still keep this suggestion in mind. As you already mentioned the protocol will stay backwards compatible, but only until a new major release. But this is exactly the situation where things *might* break and imo it would slightly improve DX if there was some kind of notice that an outdated library version might cause trouble when connecting to an updated instance of surrealdb.

Anyways thank you for your work on this great project 💕

**Comment by kearfy** [comment]
We will definitely keep it in mind, if a method get's created for this in the protocol we can always reconsider!

**Comment by netcodedev** [comment]
Great to hear!
